name: flugraph
description: A telegraph app made using flutter!

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.10.0
  audioplayers: ^0.15.1
  assets_audio_player: ^2.0.6+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/audios/